version: '3'
services:
  movie-recommender:
    build:
      context: .
    ports:
      - 5001:5001
    environment:
      - FLASK_APP=app.py
      - MONGODB_CONNECTION_STRING=mongodb://user:pass@host.docker.internal/
    restart: always
